FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG DATABASE_URL="mongodb://localhost:27017/dummy?replicaSet=rs0"
ENV DATABASE_URL=$DATABASE_URL

RUN npx prisma generate

EXPOSE 3000
CMD ["npm", "run", "start:dev"]